# "[DA] Numpy"
> "Numpy 기본"

- toc: true
- branch: master
- badges: true
- comments: true
- categories: [numpy]
- author: 도형준

# Numpy

- Numeriacal Python
- 파이썬 머신러닝 패키지인 scikit-learn에서 기본 데이터 구조로 사용되어 Numpy 배열 형태의 데이터를 사용
- 파이썬 기반 데이터 분석 환경에서 행렬 및 벡터 연산에 필요한 다양한 함수를 제공
- 메모리 소모가 많은 반복문 없이 전체 데이터 배열에 빠른 연산을 처리할 수 있는 표준 수학 함수
> 배열 : 동일한 특성(데이터 타입) 및 일정한 규칙을 가지는 여러 개의 요소가 나열되어 있는 데이터 집합
- 파이썬 list 객체를 사용할 때 보다 Numpy의 ndarray 객체를 사용하면 연산 속도가 개선되어 더 많은 데이터를 더 빠르게 처리

In [1]:
# 라이브러리 가져오기: numpy
# as 별칭 선언 이후에는 별칭으로 해당 라이브러리의 기능을 호출 할 수 있다.
# import 라이브러리명 as 별칭
import numpy as np

In [2]:
# 라이브러리 버전 확인하기
np.__version__

'1.21.5'

## Numpy 배열 : numpy.ndarray

- 다차원 배열(1차원, 2차원, 3차원)으로 입체적인 데이터 구조를 구성하고 여러 개의 데이터 방향을 가진다.
- 배열 속성 : shape, ndim, dtype 등
- 데이터 방향 : axis = 0(행/높이), 1(열/폭), 2(채널/깊이)
- 사진을 집어넣을때는 img태그 를 사용합니다.

![](img/nparr1.jpg)

### 1. 배열 생성

- np.array(data)
    - 파이썬 list객체를 전달받아 numpy list로 교환해주는 명령어
    - 배열 속성
        - shape : 구조 (행, 열, 차원)
        - ndim : 차원
        - dtype : 데이터 타입
        - size : 요소 개수 = 행 * 열 * 차원
    - 배열 메서드
        - astype() : 데이터 타입 변환(문자를 숫자로 라던지...)
    - 파이썬 내장함수를 사용한 속성값
        - type() : 객체의 자료형 확인
        - len() : 요소 내부의 자료 길이.
    - Numpy 함수를 사용한 속성
        - reshape(row, column) : 배열 재배치(1 * 12를 3 * 4 형태로 바꾼다던지...)
    - kind : 데이터 종류에 대한 구분 기호
        - b boolean
        - i 정수(int)
        - u 부호없는 정수(unsigned int, +- 개념 없이 절대값만 존재)
        - f 실수
        - c 복소 부동소수점
        - O 객체
        - S 바이트 문자열(ascii 코드, 영문자, 일부특문, 숫자)
        - U 유니코드 문자열(한글, 중국어, 태국어, 아랍어 등 영어와 다른 문자)

In [3]:
# 파이썬 1차원 리스트를 Numpy ndarray로 교환하기
tmp = [1,2,3,4,5,6]
arr = np.array(tmp)
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
# 배열 객체의 속성 - 타입 자료형
print(type(arr),type(tmp))

<class 'numpy.ndarray'> <class 'list'>


In [5]:
# 배열 객체의 속성 - 구조 확인하기: shape(row, column, dim)
# (정수,): 정수 개수의 아이템을 가진 리스트가 배열로 변환된 결과물
arr.shape

(6,)

In [6]:
# 배열 객체의 속성 - 길이 => (n,)[1DArrray]: 아이템의 개수
len(arr)

6

In [7]:
# 배열 객체의 속성 -차원
arr.ndim

1

In [8]:
# 배열 요소의 속성 - 요소의 개수
arr.size

6

In [9]:
# 배열 요소의 속성 - 데이터 타입
arr.dtype

dtype('int32')

In [11]:
# 배열 객체의 속성 - 데이터 타입의 변환: astype => 원본 데이터 유지
arr2 = arr.astype(float)
print(arr)
print(arr2)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [12]:
# 배열 구조 변환
# 기존 배열의 요소 총 개수(6개)와 변환하려는 구조의 총 개수(6개)는 일치해야 한다.
arr.reshape(2,3) #(2*3=6이므로), reshape(row,column)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Numpy 객체 정보를 좀 더 편하게 확인하기 위한 사용자 함수 정의
# 객체타입, 구조, 차원, 데이터타입, 내부자료
# 를 확인하기 위해 정의하는 함수
def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [14]:
# 리스트 요소 타입이 일관되지 않으면 우선순위에 따라 내부 데이터의 dtype이 통일된다.
# 우선순위 : str > float > int
# 서로 다른 타입의 혼합 1: int + str = str로 통일
tmp = [1,2,3,"4"]
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : <U11
    array data : 
 ['1' '2' '3' '4']


In [15]:
# 서로 다른 타입의 혼합 2: int + float = float
tmp = [1,2,3.3,4]
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : float64
    array data : 
 [1.  2.  3.3 4. ]


In [16]:
# 서로 다른 타입의 혼합 3: float + str = str
tmp = ['1',1.2,0.3]
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (3,)
    ndim : 1
    dtype : <U32
    array data : 
 ['1' '1.2' '0.3']


In [17]:
# 파이썬 2차원 리스트로 Numpy 배열 생성
# 2차원 배열의 shape 속성은 (eow, column)만 반환
tmp = [[1,2,3,4],
      [5,6,7,8]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]
 [5 6 7 8]]


In [18]:
# 파이썬 3차원 리스트로 Numpy 배열 생성
tmp = [[[1,2,3],[4,5,6]],
      [[7,8,9],[10,1,121]]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 2, 3)
    ndim : 3
    dtype : int32
    array data : 
 [[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10   1 121]]]
